# Generated by Django 3.2.7 on 2021-09-22 02:50

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('story', '0002_auto_20210921_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='story/media'),
        ),
    ]
